# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51f8f8231d989ba1880150c6956c8305b0fa6b9f566321510f71c34080093c4679d3c66a10a46c36e528176bd12d4c8d8e19af0693b5a0e86850e4c607a21a40

test:
  secret_key_base: 059bab4069f13986eaf5ec42a855cbd0664999002aa1ca5113eeff4f871ab6c5bc7108766105db991a949dc2a72b892471515509de8c0bd85804959060597a8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
